name: Create Jira Issue for Security Alerts

on:
  repository_vulnerability_alert:
    types: [create, reopen]

permissions:
  contents: read
  security-events: read

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Extract alert data
        id: alert
        run: |
          echo "PACKAGE=$(jq -r '.alert.dependency.package.name' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "SEVERITY=$(jq -r '.alert.severity' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "ADVISORY_URL=$(jq -r '.alert.advisory.references[0].url // empty' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Build Jira Issue JSON
        run: |
          cat <<EOF > issue.json
{
  "fields": {
    "project": { "key": "SEC" },
    "summary": "Security Vulnerability: ${PACKAGE} (${SEVERITY})",
    "description": "A vulnerability was detected in **${PACKAGE}**.\n\nSeverity: ${SEVERITY}\n\nDetails: ${ADVISORY_URL}",
    "issuetype": { "name": "Bug" },
    "labels": ["security", "github", "vulnerability"]
  }
}
EOF

      - name: Create Jira Issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            --data @issue.json \
            "$JIRA_URL/rest/api/3/issue"
